### ISSUE TITLE
Export with cascades and select_multiple fails

### ISSUE THREAD

**Issue by yanokwa** [getodk/build#307]
In this [School Census form.odkbuild.zip](https://github.com/getodk/build/files/8689612/School.Census.form.odkbuild.zip) form, export to XML works, but export to XLSForm fails with "Something went wrong while exporting. Please try again later."

If if uncheck cascading in Commune, it works. If I remove "Respndent_role" and replace it with a select_one, it works.

**Comment by florianm** [comment]
I can take a look at this on Monday.

**Comment by florianm** [comment]
Testing the original form, exported via XML to Central, it seems the form definition has a few typos in critical places:
* The underlying values of `Commune` are 1 for label `Limonade` and 2 for label `Cap-Haitian`.
* The cascading select field refers to `Commune` values `Limonade` (instead of 1) and various spellings of `Cap-Haitian` (none exact matches).
* The Xform does export correctly, but the code 
   ```
   <select1 ref="/data/Section_comm">
      <label ref="jr:itext('/data/Section_comm:label')"/>
      <itemset nodeset="instance('choices_Section-comm')/root/item[Commune=/data/Commune]">
        <value ref="value"/>
        <label ref="jr:itext(itextId)"/>
      </itemset>
   ```
  reads as "whatever choices_Section-comm offers for item[Commune=/data/Commune]". In this case, there are no matches.

**Comment by florianm** [comment]
I will continue troubleshooting with a repaired version of the form. As underlying values I use the lower-cased and dash-separated versions of the labels, then these are referred to consistently in the cascading select1. In the resulting Xform, all options show up as expected.
[SchoolCensusForm1.zip](https://github.com/getodk/build/files/8696893/SchoolCensusForm1.zip)

**Comment by florianm** [comment]
This is not a bug in build2xlsform, it's some dirt in the Build form def.
Export to XLSForm finds the following choices:

```
choices
{
  choices_commune: [
    { text: [Object], cascade: {}, val: 'limonade' },
    { text: [Object], cascade: {}, val: 'cape-haitien' }
  ],
  choices_Section_comm: [
    { text: [Object], cascade: [Object], val: 'roucou' },
    { text: [Object], cascade: [Object], val: 'basse-plaine' },
    { text: [Object], cascade: [Object], val: 'bois-de-lance' },
    { text: [Object], cascade: [Object], val: 'bord-de-mer' },
    { text: [Object], cascade: [Object], val: 'bande-du-nord' },
    { text: [Object], cascade: [Object], val: 'haut-du-cap' },
    { text: [Object], cascade: [Object], val: 'petite-anse' }
  ],
  choices_respondent: [
    { text: [Object], val: 'directeur' },
    { text: [Object], cascade: [], val: 'professeur' },
    { text: [Object], cascade: [], val: 'senseur' }
  ]
}
```

Notably, ` { text: [Object], val: 'directeur' },` is missing the `cascade: [],` which triggers the key error.

To narrow down the bug:

* When I add a SelectMultiple question into a form with two cascading SelectOne, the first option is missing the `cascade: [],` key. I can reproduce this by adding a new SelectMultiple.
* When I export the form to XLS, the export fails on the missing `cascade: [],` key, as build2xlsforms explicitly populates the lookups.
* When I export the form to XForm, the export works, and the form renders fine in Collect, because XForm publishes a formula for choices, not specific values (proving that XForm is the superior standard).
* When I delete the first option, XLS export works again.
* When I add the same value and label as last option (as I can't insert an option at the beginning), export still works.
* When I rename the options so the initial first option is first again, export still works.
* When I add a new SelectOne instead of a SelectMultiple after cascading SelectOnes, XLS export works, as all SelectOne choices have a `cascade: [],` key.
* When I create a new form and add only a SelectMultiple, the first option is missing the `cascade` key:

```
choices
{
  choices_untitled14: [
    { text: [Object], val: 'test' },
    { text: [Object], cascade: [], val: 'test2' }
  ]
}
```

This narrows down the bug to:

Independent of other questions in the form, inserting a SelectMultiple is missing a `cascade: []` key in the initially first and only option.

**Comment by florianm** [comment]
For the possibility that someone is waiting for a fix, I hope this could help.

Running #310 I've fixed the original form definition and exported all formats as [SchoolCensus.zip](https://github.com/getodk/build/files/8697905/SchoolCensus.zip) with following suggestions:
* All data names are url-safe (lower-cased-and-dash-separated) versions of the labels. This reduces confusion when analysing data, as labels now are self-explanatory, and in a pinch can be used as labels (replace dash with space and title case or sentence case).
* Cascading choice filters now match up.
* Language changed from "English" to "French".
* Two dud guidance hints dropped (looks like an abbreviated name).
